# Pokemon Svm

In [113]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [114]:
#Create Database
PokeData = pd.read_csv("Pokemon.csv")

n = int(len(PokeData)/2)
PokeData.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [115]:
#Legendary -1  
#not legendary -0
def Legend(i):
    if i:
        return 1
    else:
        return 0
    
PokeData["Legendary"] = PokeData["Legendary"].apply(Legend)
PokeData.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,0
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,0
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,0
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,0
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,0

In [116]:
#Training and testing data
PokeTeste = PokeData[:n]
PokeTreino = PokeData[n:]

In [117]:
#Filter only the important columns
StatsTreino = PokeTreino.loc[:,["HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]]
StatsTeste = PokeTeste.loc[:,["HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]]
StatsTreino.head()

      HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
400  110      80       90       95       90     65
401   35      64       85       74       55     32
402   55     104      105       94       75     52
403   55      84      105      114       75     52
404  100      90      130       45       65     55

In [118]:
#Linear classifier
from sklearn import svm
Classificador = svm.SVC(kernel='linear', C=1)
Classificador.fit(StatsTreino,PokeTreino["Legendary"])

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [119]:
#Testing linear classifier
ListaTeste = Classificador.predict(StatsTeste)

#Real values
x = PokeTeste.Legendary

#Comparing values
contador = 0
h = 0
for i in ListaTeste:
    if i == x[h]:
        contador+=1
    h+=1
    
prob = contador/len(x)
print("Prob of getting right: {0}".format(prob))

Prob of getting right: 0.9275

In [120]:
#Exponencial classifier
Classificador = svm.SVC(kernel='rbf',C = 1e6)
Classificador.fit(StatsTreino,PokeTreino["Legendary"])

SVC(C=1000000.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [121]:
#Testing exponencial classifier
Teste = Classificador.predict(StatsTeste)

#Real values
x = PokeTeste.Legendary

#Comparing values
contador = 0
h = 0

for i in Teste:
    if i == x[h]:
        contador+=1
    h+=1
    
prob = contador/len(x)
print("Prob of getting right: {0}".format(prob))

Prob of getting right: 0.9675

In [122]:
#Formatting type 1
#Water - 1
#Normal - 2
# ...
def Classes(i):
        lista = [
"Water",       
"Normal",       
"Grass" ,       
"Bug" ,         
"Psychic",      
"Fire",         
"Electric",     
"Rock",         
"Ground",       
"Dragon",       
"Ghost",        
"Dark",         
"Poison",       
"Fighting",     
"Steel",        
"Ice",         
"Fairy",       
"Flying" 
        ]
        
        contador = 1
        for h in lista:
            if i == h:
                return contador
            contador+= 1
PokeData["Type 1"] = PokeData["Type 1"].apply(Classes)
PokeData.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,3,Poison,318,45,49,49,65,65,45,1,0
1,2,Ivysaur,3,Poison,405,60,62,63,80,80,60,1,0
2,3,Venusaur,3,Poison,525,80,82,83,100,100,80,1,0
3,3,VenusaurMega Venusaur,3,Poison,625,80,100,123,122,120,80,1,0
4,4,Charmander,6,NaN,309,39,52,43,60,50,65,1,0

In [123]:
#Training and testing data
PokeTeste = PokeData[:n]
PokeTreino = PokeData[n:]

StatsTreino = PokeTreino.loc[:,["HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]]
StatsTeste = PokeTeste.loc[:,["HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]]

In [124]:
#Multi-Class classifier
Classificador = svm.SVC(decision_function_shape='ovr',kernel='linear')
Classificador.fit(StatsTreino,PokeTreino["Type 1"])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [125]:
#Testing Multi-Class classifier
Teste = Classificador.predict(StatsTeste)

#Real values
x = PokeTeste["Type 1"]

#Comparing values
contador = 0
h = 0

for i in Teste:
    if i == x[h]:
        contador+=1
    h+=1

prob = contador/len(x)
print("Prob of getting right: {0}".format(prob))

Prob of getting right: 0.2375